### ISSUE TITLE
Secure connections https

### ISSUE THREAD

**Issue by elainewlin** [elainewlin/MusicParsed#50]
Add a certificate: https://letsencrypt.org/.

Note to self: should probably add to FoodParsed + elainewlin as well.

**Comment by andersk** [comment]
Heroku can do this [automatically](https://devcenter.heroku.com/articles/automated-certificate-management) if you’re paying them.

**Comment by elainewlin** [comment]
Investigate moving to [Google AppEngine](https://cloud.google.com/appengine/) instead of Heroku.

**Comment by elainewlin** [comment]
Google AppEngine appears to be more expensive. I upgraded to the Hobby tier (paying $7/month), and this now happens automatically.
