### ISSUE TITLE
12/19 uke@yelp song fixes

### ISSUE THREAD

**Issue by elainewlin** [elainewlin/MusicParsed#54]
http://www.musicparsed.com/song/eagles/hotel_california
missing last chorus?
http://www.musicparsed.com/song/the_beatles/while_my_guitar_gently_weeps
Bbm75 broken chord
https://tabs.ultimate-guitar.com/tab/james_taylor/youve_got_a_friend_chords_56577
add
http://www.musicparsed.com/song/green_day/boulevard_of_broken_dreams
and I'm the only one and I walk alone
       A      Em
I walk alone, I walk alone
        A     Em
I walk alone, I walk a..

**Comment by andersk** [comment]
> http://www.musicparsed.com/song/the_beatles/while_my_guitar_gently_weeps
> Bbm75 broken chord

Transposed from Gm75, but it’s supposed to be Gm7♭5.
